version: "3.95"  # optional since v1.27.0
services:

  postgres:
    container_name: ctagdbcontainer
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ctagdb
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/data:/tmp
    ports:
      # localport:containerport
      - '5432:5432'